monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            firephp:
                type: firephp
                level: info
            chromephp:
                type: chromephp
                level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: critical
                handler: grouped
            grouped:
                type: group
                members: [streamed, deduplicated]
            streamed:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            deduplicated:
                type: deduplication
                handler: symfony_mailer
            symfony_mailer:
                type: symfony_mailer
                from_email: "error@trials-of-banshee.com"
                to_email: "error@trials-of-banshee.com"
                subject: "Trials of Banshee - Error - %%message%%"
                level: debug
                formatter: monolog.formatter.html
                content_type: text/html
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
