security:
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        main:
            entity:
                class: App\Entity\User
                property: membershipId

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: main
            custom_authenticators:
                - App\Security\DestinyAuthenticator
            remember_me:
                secret: "%kernel.secret%"
                always_remember_me: true
                signature_properties: ['accessToken', 'refreshToken']

