version: '3.8'

services:
  php-tob:
    build: ./docker/php-apache
    container_name: tob-php-apache
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
      - 443
    volumes:
      - ./:/var/www/html

  mysql-tob:
    image: mysql:5.7
    container_name: mysql-tob
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tob
      MYSQL_USER: tob
      MYSQL_PASSWORD: tob
    ports:
      - 3306
    expose:
      - 3306
    volumes:
      - tob-db:/var/lib/mysql

volumes:
  tob-db: null
